#!/bin/bash

echo "🚀 HR Portal - Render Deployment Guide"
echo "============================================"
echo ""

echo "📋 Prerequisites:"
echo "✅ Code pushed to GitHub"
echo "✅ Render account created"
echo ""

echo "🔧 Deployment Options:"
echo ""
echo "Option 1: Blueprint Deployment (Recommended)"
echo "=============================================="
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New' → 'Blueprint'"
echo "3. Connect your GitHub repository: SiddharthPh/achievers"
echo "4. Render will auto-detect render.yaml and deploy both services"
echo ""

echo "Option 2: Manual Service Creation"
echo "=================================="
echo "Backend Service:"
echo "1. New → Web Service"
echo "2. Connect GitHub repo"
echo "3. Build Command: cd backend && pip install -r requirements.txt"
echo "4. Start Command: cd backend && python app.py"
echo "5. Environment: Python 3"
echo "6. Environment Variables:"
echo "   - PORT: 10000"
echo "   - FLASK_ENV: production"
echo ""
echo "Frontend Service:"
echo "1. New → Static Site"
echo "2. Connect GitHub repo"
echo "3. Build Command: cd frontend && npm install && npm run build"
echo "4. Publish Directory: frontend/dist"
echo "5. Environment Variables:"
echo "   - VITE_API_URL: [YOUR_BACKEND_URL]"
echo ""

echo "🔗 Your backend will be available at:"
echo "https://hr-portal-backend.onrender.com"
echo ""
echo "🔗 Your frontend will be available at:"
echo "https://hr-portal-frontend.onrender.com"
echo ""

echo "🧪 Local Testing:"
echo "Backend: http://localhost:10000"
echo "Frontend: http://localhost:5173"
echo ""

echo "📊 Health Check:"
echo "GET /api/health should return:"
echo '{"service":"HR Portal API","status":"healthy"}'
echo ""

echo "Need help? Check RENDER_DEPLOYMENT.md for detailed instructions!"
